#!/usr/bin/env python3
"""params.json -> build/params_gen.h (enum P_<KEY>, per-param name/type) and build/pluginlist-entry.xml."""
import json
import os

ROOT = os.path.dirname(os.path.abspath(__file__))
spec = json.load(open(os.path.join(ROOT, "params.json")))
out = os.path.join(ROOT, "build")
os.makedirs(out, exist_ok=True)
types = {"stepper": "T_STEPPER", "trigger": "T_TRIGGER", "float": "T_FLOAT", "readout": "T_READOUT", "slot": "T_SLOT"}
lines = ["/* generated by gen_params.py from params.json - do not edit */", "#pragma once",
         "enum { T_STEPPER, T_TRIGGER, T_FLOAT, T_READOUT, T_SLOT };",
         "typedef struct { const char *key, *name; int type; float min, max, def; } param_t;", "enum {"]
lines += ["    P_%s," % p["key"].upper() for p in spec["params"]]
lines += ["    NPARAMS", "};", "static const param_t PARAMS[NPARAMS] = {"]
for p in spec["params"]:
    lo, hi = p.get("min", 0), p.get("max", 1)
    d = p.get("default", lo)
    norm = (d - lo) / (hi - lo) if hi > lo else 0
    lines.append('    {"%s", "%s", %s, %rf, %rf, %rf},' % (p["key"], p["name"], types[p["type"]], float(lo), float(hi), float(norm)))
lines += ["};", '#define PLUG_NAME "%s"' % spec["name"], '#define PLUG_VENDOR "%s"' % spec["vendor"],
          "#define PLUG_UID 0x%08x /* '%s' */" % (int.from_bytes(spec["uid"].encode(), "big"), spec["uid"]),
          "#define PLUG_VERSION %d" % spec["version"]]
open(os.path.join(out, "params_gen.h"), "w").write("\n".join(lines) + "\n")
so = spec["name"].lower().replace(" ", "")
open(os.path.join(out, "pluginlist-entry.xml"), "w").write(
    '<PLUGIN name="{n}" descriptiveName="{n}" format="VST" category="Synth" manufacturer="{v}" version="1.0" '
    'file="/sdcard/vst/{so}.so" uid="{u:x}" isInstrument="1" fileTime="0" infoUpdateTime="0" numInputs="0" '
    'numOutputs="2" isShell="0"/>\n'.format(n=spec["name"], v=spec["vendor"], so=so,
                                           u=int.from_bytes(spec["uid"].encode(), "big")))
print("params_gen.h: %d params" % len(spec["params"]))
